services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - astrogators_network

  comlink:
    image: ghcr.io/swgoh-utils/swgoh-comlink:latest
    restart: always
    environment:
      - APP_NAME=TheAstrogatorsTable
      - LOG_LEVEL=info
      - ACCESS_KEY=${SWGOH_COMLINK_ACCESS_KEY}
    ports:
      - "3200:3000"
    networks:
      - astrogators_network

  asset-extractor:
    image: ghcr.io/swgoh-utils/swgoh-ae2:latest
    restart: always
    ports:
      - "3400:3400"
    networks:
      - astrogators_network

volumes:
  postgres_data:

networks:
  astrogators_network:
