services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - astrogators_network

  redis:
    image: redis:latest
    container_name: astrogators_redis
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

  comlink:
    image: ghcr.io/swgoh-utils/swgoh-comlink:latest
    restart: always
    environment:
      - APP_NAME=TheAstrogatorsTable
      - LOG_LEVEL=info
      - ACCESS_KEY=${SWGOH_COMLINK_ACCESS_KEY}
    ports:
      - "3200:3000"
    networks:
      - astrogators_network

  asset-extractor:
    image: ghcr.io/swgoh-utils/swgoh-ae2:latest
    restart: always
    ports:
      - "3400:3400"
    networks:
      - astrogators_network

volumes:
  postgres_data:
  redis-data:

networks:
  astrogators_network: